name: Deploy Images to GHCR

on:
  pull_request: 
    branches:
      - main
  workflow_dispatch: 

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  BUILD_DATE: $(date +'%d%m%Y')

jobs:

  # remove-console-logs:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Remove console.log statements
  #       run: |
  #         find ./src -type f -name "*.ts" -print0 | xargs -0 sed -i '/console\.log/d'

  #     - name: Check for remaining console.log
  #       run: |
  #         if grep -r "console.log" ./src; then
  #           echo "❌ console.log statements still found!"
  #           exit 1
  #         else
  #           echo "✅ No console.log statements found."
  #         fi

  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: install dependencies
        run: npm install
      
      - name: Run unit tests
        run: npm run test
      
      - name: Run integration tests
        run: npm run test:e2e

  build-push-store-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Extract PR Number
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo 'PR_NUMBER=0' >> $GITHUB_ENV
          fi

      - name: Generate Image Tag
        run: echo "IMAGE_TAG=${BUILD_DATE}-${PR_NUMBER}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo_name
        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print tolower($2)}')" >> $GITHUB_ENV

      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: 'Build Inventory Image'
        run: |
            docker build --tag ghcr.io/karimdevwm/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} .
            docker push ghcr.io/karimdevwm/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}

  deploy:
    needs: build-push-store-docker-image
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy using Ansible
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/task_service/deploy/
            ansible-playbook -i inventory deploy_microservices.yml